services:
  tabby:
    image: ghcr.io/eugeny/tabby-web:latest
    restart: always
    depends_on:
      - db
    command: >
      sh -c "find /app -name index.html; /start.sh"
    environment:
      - DATABASE_URL=mysql://tabby:password@db/tabby
      - APP_URL=https://tabby.0mod.com
      - PORT=8000
      - GUNICORN_CMD_ARGS=--bind=0.0.0.0:8000
      - SOCIAL_AUTH_GITHUB_KEY=${SOCIAL_AUTH_GITHUB_KEY}
      - SOCIAL_AUTH_GITHUB_SECRET=${SOCIAL_AUTH_GITHUB_SECRET}
    volumes:
      - tabby-data:/app/data

  db:
    image: mariadb:10.7.1
    restart: always
    environment:
      - MARIADB_DATABASE=tabby
      - MARIADB_USER=tabby
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}
    volumes:
      - tabby-db:/var/lib/mysql

volumes:
  tabby-data:
  tabby-db:
